//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _08_LTUDDN_VuKhuongDuy_20103100764.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class MuonTra
    {
        [Key, Column(Order = 0)]
        [Required]
        public int MaDG { get; set; }
        [Key, Column(Order = 1)]
        [Required]
        public string TenSach { get; set; }

        [Required]
        public Nullable<System.DateTime> NgayMuon { get; set; }

        [Required]
        public Nullable<decimal> GiaSach { get; set; }
    
        public virtual DocGia DocGia { get; set; }
    }
}
