//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuLam_de3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class KetQua
    {
        [Key, Column(Order = 0)]
        [Required]
        public int MaNV { get; set; }

        [Key, Column(Order = 1)]
        [Required]
        public string TenSP { get; set; }
        [Required]
        public Nullable<decimal> DonGia { get; set; }
        [Required]
        [Range(1,50,ErrorMessage ="So luong tu 1 den 50")]
        public Nullable<int> SoLuong { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
